//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCO.CapaDatos.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenXProducto
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OrdenId { get; set; }
        public Nullable<System.Guid> ProductoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Orden Orden { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
